name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        distribution: [ 'zulu', 'temurin', 'liberica' ]
        java: [ '17' ]
    name: Build with Java ${{ matrix.java }} (${{ matrix.distribution }})

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
        cache: maven
    - name: Build
      run: mvn -B compile --file pom.xml
    - name: Test and analysis
      run: mvn -B verify --file pom.xml
    - name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./jacoco-report-aggregate/target/site/jacoco-aggregate/jacoco.xml
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Upload to Sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B sonar:sonar -Dsonar.organization=lecousin -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=lecousin_lc-commons -DprojectName=lc-commons -Dsonar.projectName=lc-commons
